server:
  port: 8081
  servlet:
    context-path: /demo
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    database: 3
    host: 221.12.172.57
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 100ms
    password: Longshine@01
    port: 26379


